### ISSUE TITLE
Basic Permissions

### ISSUE THREAD

**Issue by ColinW520** [ColinW520/hydra#20]
![image](https://user-images.githubusercontent.com/3529146/28747914-d1c24a68-746f-11e7-90a4-38e7c9854feb.png)

We need to implement these very basic permission levels.

Only Admins can do the following things
- Admin can edit other users
- Admin can invite other users
- Admin can change org settings
- Admin can buy lines
- Admins can manipulate line settings

**Comment by browning25** [comment]
Testing required 
Need documentation for what checking the box gives a user

Only Admins can do the following things
- Admin can edit other users
- Admin can invite other users
- Admin can change org settings
- Admin can buy lines
- Admins can manipulate line settings

**Comment by browning25** [comment]
Any movement on this one?  I see we can grant admin privileges when we invite a new user.  If we do not check the Admin box, will it default to Supervisor?  I assume Supervisor privileges are as follows:

- Supervisor can send text messages

- Supervisor can upload new and edit current contacts

**Comment by ColinW520** [comment]
None since August really... just needs testing I think. should be resolvable. I think we can close this out until we have more pressing requirements that define a new issue. Up to you to close.

**Comment by browning25** [comment]
@ColinW520 -- I'm ready to close if you can confirm that the supervisor role does not allow someone to: 

- [ ] upload a CSV file. 
- [ ] add a new twilio line

These are the 2 biggest things we need to limit for supervisors, in my mind.

Also, I think it would be good to see the designation of "Supervisor Privileges" on each of the "Users" profiles

**Comment by ColinW520** [comment]
close'm up close'm up!

**Comment by browning25** [comment]
Closing this issue.
