### ISSUE TITLE
Create a configurable AutoResponder

### ISSUE THREAD

**Issue by ColinW520** [ColinW520/hydra#27]
For organizations that do not want their contacts to be able to reply to messages, allow them to configure an auto-response.

- [ ] Add `sms_auto_response` to individual Line settings
- [ ] Add adaptation logic to Twilio::Messages::ReceivingController

**Comment by ColinW520** [comment]
This is very tightly linked to #32, and will most likely be shipped together.

**Comment by ColinW520** [comment]
@browning25 this is also ready to be tested

- [ ] When I send a text message to a line configured with an auto-response, I should receive the auto-response.

**Comment by browning25** [comment]
Confirmed functionality.  Closing issue.
