### ISSUE TITLE
Make call response message customizable

### ISSUE THREAD

**Issue by browning25** [ColinW520/hydra#32]
Allow admins to specify the message that is spoken if someone tries to call a line that is not setup for forwarding. 

Also, allow admins to reject calls outright if they want.

**Comment by ColinW520** [comment]
This is done, along with some ancillary functionality...needs tested. 

Testing items:

- [ ] If the 'reject all calls' box is selected, call should never connect when the line # is dialed.
- [ ] If the 'Auto Response' field has text in it, it should be read aloud when the call to the line is connected.
- [ ] If the 'Forwarding #' is set, the call should be forwarded to that number.

**Comment by browning25** [comment]
- [ ] Reject all calls functionality works

- [ ] Auto SMS Text response works

- [ ] Voice auto response did not work. "We are sorry, an application error has occurred"

- [ ] Will test call forwarding when I get access to Cassie's phone.

**Comment by ColinW520** [comment]
just shipped some fixes to these. got the response and your voicemail when I tested -- give it a whirl!
