### ISSUE TITLE
Twilio Bed Wetting.

### ISSUE THREAD

**Issue by browning25** [ColinW520/hydra#33]
When creating a new account on TextMy.Team, and connecting their Twilio account, the user is asked to 'connect or create a twilio account'. Once on the Twilio page, submitting the form results in a 500 error. We need to reproduce it, screen capture it, and send it to Twilio.

**Comment by browning25** [comment]
I need to create a new TMT account process, including creating a new Twilio account in the process.

**Comment by browning25** [comment]
Also create an account without any Stripe account linked

**Comment by browning25** [comment]
@ColinW520 - are you ready for me to test with a new account setup?

**Comment by ColinW520** [comment]
reasons why I don't want to test this yet:

1) it costs money

...

@browning25 -- your call on this one. I say we punt for now, since any new sign-ups will be individuals we hand-hold.

**Comment by browning25** [comment]
Yes, agree, let's punt for now based on our previous discussions. We will continue to monitor this in the Beta release.
