### ISSUE TITLE
Messaging Activity Summaries

### ISSUE THREAD

**Issue by ColinW520** [ColinW520/hydra#34]
One-by-one email notifications _sound_ annoying. Let's send out daily/weekly/monthly summaries! Lines should _have many_ summary subscriptions (multiple user subscribers)

**Comment by browning25** [comment]
Was thinking this could look something like this (see attached)
[TMT Summary Email Sketch.docx](https://github.com/ColinW520/hydra/files/1231105/TMT.Summary.Email.Sketch.docx)

**Comment by ColinW520** [comment]
@browning25 this is ready to test & _promote_

Testing criteria:

- [ ] Go to your user profile, and check all the new notification boxes
- [ ] Send the testing # a message, see if you get a notificatin
- [ ] see if you get an email between 8-9 AM the next morning wiht a summary
- [ ] see if you get an email monday AM with a summary

should look a bit like this:

![image](https://user-images.githubusercontent.com/3529146/30360060-c89ae03a-9814-11e7-8cce-871127572c35.png)

**Comment by ColinW520** [comment]
also -- once done -- we need to discuss an announcement plan for users.

**Comment by browning25** [comment]
Got the instant notification after sending a message!!  Will need to wait to see how the weekly updates look. So far, so good!

**Comment by ColinW520** [comment]
The weekly should be sending...it's not erroring...let's see what happens on Monday

**Comment by ColinW520** [comment]
Success! It's ugly, but it's there.
![image](https://user-images.githubusercontent.com/3529146/31085851-de006ba4-a75d-11e7-9742-1400a3ffd38d.png)

Ready to close this when you are @browning25

**Comment by browning25** [comment]
Yea, I think we have what we need to get started. Closing.
