### ISSUE TITLE
Help and FAQs Page

### ISSUE THREAD

**Issue by browning25** [ColinW520/hydra#35]
Create a page that shows help and facts (like Admin privileges, troubleshooting, tutorials on sending a message, etc)

Andy will write this up in MS Word

**Comment by browning25** [comment]
First draft here.  I could not find any FAQ pages on other websites to base this off of. 

Also, figured we would keep the Help section pretty brief.  Unless you have specific trouble-shooting steps for uploading contacts?
[FAQ.docx](https://github.com/ColinW520/hydra/files/1241896/FAQ.docx)

**Comment by ColinW520** [comment]
...how did I miss this...

New dev requirements:

- [ ] Create a model: **Question**, attributes: text, answer (html friendly)
- [ ] create a faqs index
- [ ] creat an admin interface for creating questions and answers
- [ ] let andy loose!

**Comment by browning25** [comment]
I really like your approach!  Let me know when it is done and I will get everything added.

**Comment by ColinW520** [comment]
@browning25 the functionality is complete, it's probably a separate issue for the content to be added. LMK if you need anything else here.

**Comment by browning25** [comment]
@ColinW520 - The list of questions will likely grow/change, but let me know what you think of the latest version.

**Comment by ColinW520** [comment]
Taking this convo to Skype...verified questions are showing up even when logged out. Should be good to close!

**Comment by browning25** [comment]
Agree on closing.  I will update the questions to reflect the appropriate customer service model as well as customers receiving 2 charges, not invoices, each month.
