### ISSUE TITLE
Deliver Anniversary and Birthday Fields for Employees

### ISSUE THREAD

**Issue by browning25** [ColinW520/hydra#38]
Create 2 additional columns for employees that show their company anniversary and birthday for reference.

**Comment by browning25** [comment]
It looks like you were able to add these fields for AUG's upload.  Ready for closure?

**Comment by browning25** [comment]
- [ ] Add Birth Date to form

**Comment by ColinW520** [comment]
Reprioritizing this...it's barely being used as-is. want to focus on functionality that extends value.

**Comment by ColinW520** [comment]
Closing this out. It feels like it's out of range/scope. The big feature would be 'custom user data'. That's what we'll start scoping should requests like these grow.
