### ISSUE TITLE
Make CSV imports compatible with a wider possibility of CSV files

### ISSUE THREAD

**Issue by ColinW520** [ColinW520/hydra#40]
So, this isn't exactly a bug, but it's still aberrant behavior. The importer is currently _extremely_ strict regarding the import file types it is willing to work with. Notably, it rejects anything that isn't a PURE CSV file, including Excel-exported csv's, plaintext csvs, and more. Believe it or not ( I know, it's stupid ) -- almost every word processing application encodes csv files differently...for some reason.

To make contact imports more useful for ALL, we need to accept a wider array of file types. This gets tricky -- because we still need to be able to parse the thing, and for that we need it to be amenable to csv-ish commands.

This is the first in a range of issues around imports, including better progress transparency, error messages, and more.

Here are the test cases we need to support:

- [x] As a Windows user, when I save a properly formatted EXCEL spreadsheet without any extraneous commas as a "CSV", then I should be able to import that sheet. 
- [x] As an OSX user, when I save a properly formatted EXCEL spreadsheet without any extraneous commas as a "CSV", then I should be able to import that sheet. 
- [x] As CHROME user, when I save a properly formatted GOOGLE SHEETS spreadsheet without any extraneous commas as a "CSV", then I should be able to import that sheet. 

Bonus points: write Meta tests that support these requirements.

**Comment by ColinW520** [comment]
@browning25 -- I was able to test using Chrome and OSX. Can you test Windows?

**Comment by browning25** [comment]
I could not get the test file to upload.  Can you double check to make sure I have the formatting correct? I tried every variation of CSV I could save the file as.  No luck.  (The attached file is XLSX, but I tried uploading CSV files, Github doesnt support CSV file sharing).

[TMT Test Upload.xlsx](https://github.com/ColinW520/hydra/files/1227969/TMT.Test.Upload.xlsx)

**Comment by ColinW520** [comment]
@browning25 we're going to need to test that live. It's gotta work from a Windows machine to an actual server IMO

**Comment by ColinW520** [comment]
@browning25 -- i made more changes. I'm still not 100% confident I can test this effectively though. Would you mind giving it another whirl?

**Comment by browning25** [comment]
@ColinW520 -- I was able to successfully upload a CSV file. 
1) The first upload added a new person successfully. 
2) Second upload contained a name/info that was already loaded, just had a new tag added (it updated properly).
3) The third upload changed the spelling of a last name, but kept all the other information the same. It properly updated the last name and kept everything else the same (no duplicate was created - great work!)
4) I could not download the example file, however

I think this has been adequately addressed!

**Comment by ColinW520** [comment]
Awesome. Download file button resolved tonight. Close it if you're satisfied!

**Comment by browning25** [comment]
@ColinW520  -- I was able to download the spreadsheet. Only thing I noticed was that on my spreadsheet, it had Derek Schillaci's actual phone number on it.  Is this the same spreadsheet that everyone will see when they download a sample file?  If so, we need to change Derek's phone number just in case.  Otherwise, looks great and ready to close.

**Comment by ColinW520** [comment]
made changes and saved -- should be closable

**Comment by browning25** [comment]
Verified the changes and ready to close.
