### ISSUE TITLE
Tagging and Sorting Contacts

### ISSUE THREAD

**Issue by browning25** [ColinW520/hydra#45]
Creating this issue to fine-tune some of the sorting issues we have been working.  Upon trying to sort my contacts, I found the following issues:

- [x] The "select all" check box does not select any contacts after I sort by tag or title

- [x] Is there a way for there to be "live updating" after a second tag is typed into the sorting field (instead of having to click "update")? This is a really minor thing, not sure how difficult it is.

**Comment by ColinW520** [comment]
On the 'live updating' point:

I think we need to either make **everything** live updating -- or  -- nothing live updating -- right now it's _supposed_ to live update after the :blur event (aka, any change to any field) -- but it's not the most performant solution, and after some over-the-shoulder usage testing, I'm not sure it's even desired...

more to come, just some preliminary work notes. either way -- whatever direction we pick -- it should work...

**Comment by ColinW520** [comment]
Ready to close this, the second point is more-so it's own issue than a bug at this point

**Comment by browning25** [comment]
Concur
